# Configuration template for uitest-agent
# Copy this file to config.yaml and update with your own values

# Your Google API key
google_api_key: "YOUR_GOOGLE_API_KEY_HERE"

# Use Vertex AI instead of direct API access
use_vertex_ai: false

# Model name to use
model_name: "gemini-2.5-pro-preview-03-25"

# Optional: Path to local mobile MCP tool (if not specified, will use npx -y mobilenext/mobile-mcp@latest)
# mobile_mcp_path: "/path/to/local/mobile-mcp/index.js"

# Optional: Path to local web MCP tool (if not specified, will use npx @playwright/mcp@latest)
# web_mcp_path: "/path/to/local/playwright-mcp/index.js"